included:
- Sources
line_length:
  warning: 165
  ignores_comments: true
function_body_length:
  warning: 70
  error: 100
file_length:
  warning: 500
  error: 600
large_tuple:
  warning: 3
nesting:
  type_level:
    warning: 2
disabled_rules:
  - colon
  - identifier_name
  - type_name
  - cyclomatic_complexity
  - pattern_matching_keywords
  - todo
